FROM python:3.10-slim

# Add build tools and packet capture dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libffi-dev \
    libpcap-dev \
    tcpdump \
    tshark \
    iproute2 \
    curl \
    && pip install --upgrade pip

# Install Python packages
RUN pip install scapy pyshark flask netifaces

WORKDIR /sniffer
COPY sniffer/ /sniffer/

ENTRYPOINT ["python", "listener_api.py"]
