services:
  ospd-openvas:
    networks:
      l4_net:
        ipv4_address: 10.4.50.250
      l3_net:
        ipv4_address: 10.3.50.250
      l2_net:
        ipv4_address: 10.2.50.250
      net_10_1_1:
        ipv4_address: 10.1.1.249
      net_10_1_2:
        ipv4_address: 10.1.2.249
      oob_mgmt:
        ipv4_address: 172.31.250.249

networks:
  l4_net:
    external: true
    name: iaea_rcs_demo_l4_net
  l3_net:
    external: true
    name: iaea_rcs_demo_l3_net
  l2_net:
    external: true
    name: iaea_rcs_demo_l2_net
  net_10_1_1:
    external: true
    name: iaea_rcs_demo_net_10_1_1
  net_10_1_2:
    external: true
    name: iaea_rcs_demo_net_10_1_2
  oob_mgmt:
    external: true
    name: iaea_rcs_demo_oob_mgmt
