services:
  db:
    image: postgres:17
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - appnet

  web:
    build: .
    command: python cyber_pen_test/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PYTHONPATH=/code
    depends_on:
      - db
      - redis
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - appnet

  sniffer:
    build:
      context: .
      dockerfile: sniffer/Dockerfile.sniffer
    command: python /sniffer/listener.py
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - .:/code

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A cyber_pen_test worker --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PYTHONPATH=/code

networks:
  appnet:

