services:
  web:
    environment:
      PYTHONUNBUFFERED: "1"
      DJANGO_LIVE_RELOAD: "1"
    volumes:
      - .:/code
      - ../ics-risk-assessment:/opt/ics-risk-assessment
  celery:
    volumes:
      - .:/code
      - ../ics-risk-assessment:/opt/ics-risk-assessment
