"""
Django settings for cyber_pen_test project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def read_secret(name: str, default: str = "") -> str:
    file_path = os.environ.get(f"{name}_FILE")
    if file_path:
        try:
            return Path(file_path).read_text().strip()
        except Exception:
            return default
    return os.environ.get(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = read_secret(
    "DJANGO_SECRET_KEY",
    default="django-insecure-e+(qsiwl=z+jizb8=ujy!+ay%r8xcpv2pz@=(c9r#bs-9%c!ov",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.137.4.115',  # Specific host that needs access
    # Subnet patterns for broader access:
    '10.137.4.*',    # Allows all IPs in 10.137.4.x range
    '10.137.*.*',    # Allows all IPs in 10.137.x.x range
    # For development/testing - allows all IPv4 (less secure):
    # '0.0.0.0',
    # Add additional specific IPs as needed:
    # '192.168.1.100',
    # '10.0.0.50',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'sliver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ASGI Application for WebSocket support
ASGI_APPLICATION = 'cyber_pen_test.asgi.application'

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Redis for channel layer
        },
    },
}

ROOT_URLCONF = 'cyber_pen_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cyber_pen_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
# CELERY_BROKER_URL = 'redis://localhost:6379/0'  # or 'redis://redis:6379/0'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "dashboard/static",
]
# Where collectstatic will put the static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media uploads (loot files, artifacts)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Sliver implant artifact storage (override with SLIVER_ARTIFACT_DIR env var)
SLIVER_ARTIFACT_DIR = os.environ.get('SLIVER_ARTIFACT_DIR', str(BASE_DIR / 'sliver_artifacts'))

# ICS Risk Assessment API
RISK_ASSESSMENT_API_URL = os.environ.get('RISK_ASSESSMENT_API_URL', 'http://127.0.0.1:7890')

# SIEM ingest settings
SIEM_INGEST_TOKEN = read_secret("SIEM_INGEST_TOKEN", "")
SIEM_INGEST_TOKEN_REQUIRED = os.environ.get("SIEM_INGEST_TOKEN_REQUIRED", "1") == "1"
SIEM_MAX_INGEST_BATCH = int(os.environ.get("SIEM_MAX_INGEST_BATCH", "500"))

# Agent API settings
AGENT_API_TOKEN = read_secret("AGENT_API_TOKEN", "")
AGENT_API_TOKEN_REQUIRED = os.environ.get("AGENT_API_TOKEN_REQUIRED", "1") == "1"

# OpenSearch (SIEM log store)
OPENSEARCH_ENABLED = os.environ.get("OPENSEARCH_ENABLED", "0") == "1"
OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://opensearch:9200")
OPENSEARCH_INDEX_PREFIX = os.environ.get("OPENSEARCH_INDEX_PREFIX", "siem-events")
OPENSEARCH_USER = os.environ.get("OPENSEARCH_USER", "")
OPENSEARCH_PASS = read_secret("OPENSEARCH_PASS", "")
OPENSEARCH_VERIFY_TLS = os.environ.get("OPENSEARCH_VERIFY_TLS", "1") == "1"

# Threat intel
THREAT_INTEL_ENABLED = os.environ.get("THREAT_INTEL_ENABLED", "1") == "1"

# TLS / secure cookie settings (enable in production)
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "0") == "1"
SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "0") == "1"
CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "0") == "1"
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if os.environ.get("DJANGO_SECURE_PROXY_SSL", "0") == "1"
    else None
)


CELERY_BEAT_SCHEDULE = {
    'poll-openvas-results-every-5min': {
        'task': 'dashboard.tasks.poll_openvas_results',
        'schedule': crontab(minute='*/5'),
    },
}
