# Generated by Django 3.2.25 on 2025-05-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='dashboard.node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='dashboard.node')),
            ],
        ),
    ]
