# Generated by Django 3.2.25 on 2025-05-06 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cidr', models.CharField(max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('result_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(default='online', max_length=32),
        ),
        migrations.AddField(
            model_name='link',
            name='scan_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dashboard.scanrun'),
        ),
        migrations.AddField(
            model_name='node',
            name='scan_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='dashboard.scanrun'),
        ),
    ]
