# Generated by Django 3.2.25 on 2025-05-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_agentcommand_commandresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='agent_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='scan_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='dashboard.scanrun'),
        ),
        migrations.CreateModel(
            name='NodeInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dashboard.node')),
            ],
        ),
    ]
