# Generated by Django 3.2.25 on 2025-06-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20250509_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulernability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField()),
                ('cve_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dashboard.scanrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='vulernability',
            index=models.Index(fields=['host_ip', 'cve_id'], name='dashboard_v_host_ip_f35b5a_idx'),
        ),
    ]
