# Generated by Django 3.2.25 on 2025-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20250624_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='openvas_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='scan_type',
            field=models.CharField(default='ping', max_length=32),
        ),
    ]
