# Generated by Django 3.2.25 on 2025-08-24 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20250624_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('kernel', models.CharField(blank=True, max_length=128)),
                ('arch', models.CharField(blank=True, max_length=32)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=5)),
                ('address', models.GenericIPAddressField()),
                ('prefixlen', models.PositiveSmallIntegerField()),
                ('broadcast', models.GenericIPAddressField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=16, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_link_local', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_packets', models.BigIntegerField(default=0)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('rx_errors', models.BigIntegerField(default=0)),
                ('rx_dropped', models.BigIntegerField(default=0)),
                ('rx_overruns', models.BigIntegerField(default=0)),
                ('rx_frame', models.BigIntegerField(default=0)),
                ('tx_packets', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('tx_errors', models.BigIntegerField(default=0)),
                ('tx_dropped', models.BigIntegerField(default=0)),
                ('tx_overruns', models.BigIntegerField(default=0)),
                ('tx_carrier', models.BigIntegerField(default=0)),
                ('tx_collisions', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalNetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iface_name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('ethernet', 'Ethernet'), ('bridge', 'Bridge'), ('loopback', 'Loopback'), ('veth', 'Veth'), ('docker_bridge', 'DockerBridge'), ('libvirt_bridge', 'LibvirtBridge'), ('other', 'Other')], default='other', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('mtu', models.PositiveIntegerField(blank=True, null=True)),
                ('txqueuelen', models.PositiveIntegerField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('supports_broadcast', models.BooleanField(default=False)),
                ('supports_multicast', models.BooleanField(default=False)),
                ('managed_by', models.CharField(choices=[('kernel', 'Kernel'), ('docker', 'Docker'), ('libvirt', 'Libvirt'), ('other', 'Other')], default='other', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField()),
                ('cve_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vulernability',
            name='scan_run',
        ),
        migrations.AlterModelOptions(
            name='scanrun',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='commandresult',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.agentcommand'),
        ),
        migrations.AlterField(
            model_name='link',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='scan_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('openvas', 'OpenVAS')], default='ping', max_length=32),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('scan_run', 'source', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeinterface',
            unique_together={('node', 'name')},
        ),
        migrations.AddIndex(
            model_name='agentcommand',
            index=models.Index(fields=['agent_id', 'acknowledged', 'created'], name='dashboard_a_agent_i_fe91eb_idx'),
        ),
        migrations.AddIndex(
            model_name='commandresult',
            index=models.Index(fields=['agent_id'], name='dashboard_c_agent_i_cc43c5_idx'),
        ),
        migrations.AddIndex(
            model_name='commandresult',
            index=models.Index(fields=['timestamp'], name='dashboard_c_timesta_d66bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['scan_run'], name='dashboard_l_scan_ru_9b4c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['source'], name='dashboard_l_source__130564_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['destination'], name='dashboard_l_destina_b42497_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['ip_address'], name='dashboard_n_ip_addr_101897_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['agent_id'], name='dashboard_n_agent_i_a3179d_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeinterface',
            index=models.Index(fields=['ip'], name='dashboard_n_ip_6180e6_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeinterface',
            index=models.Index(fields=['mac'], name='dashboard_n_mac_d04503_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['timestamp'], name='dashboard_s_timesta_1de1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['status', 'scan_type'], name='dashboard_s_status_2be12e_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='dashboard_v_severit_1cb35b_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['last_modified'], name='dashboard_v_last_mo_533e39_idx'),
        ),
        migrations.DeleteModel(
            name='Vulernability',
        ),
        migrations.AddField(
            model_name='scanvulnerability',
            name='scan_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dashboard.scanrun'),
        ),
        migrations.AddField(
            model_name='localnetworkinterface',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dashboard.host'),
        ),
        migrations.AddField(
            model_name='localnetworkinterface',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaves', to='dashboard.localnetworkinterface'),
        ),
        migrations.AddField(
            model_name='interfacestats',
            name='iface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dashboard.localnetworkinterface'),
        ),
        migrations.AddField(
            model_name='interfaceaddress',
            name='iface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='dashboard.localnetworkinterface'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['agent_id'], name='dashboard_h_agent_i_af9c82_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['hostname'], name='dashboard_h_hostnam_83e4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scanvulnerability',
            index=models.Index(fields=['host_ip', 'cve_id'], name='dashboard_s_host_ip_cee1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='scanvulnerability',
            index=models.Index(fields=['scan_run'], name='dashboard_s_scan_ru_c48ecc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scanvulnerability',
            unique_together={('scan_run', 'host_ip', 'cve_id')},
        ),
        migrations.AddIndex(
            model_name='localnetworkinterface',
            index=models.Index(fields=['iface_name'], name='dashboard_l_iface_n_7e82a9_idx'),
        ),
        migrations.AddIndex(
            model_name='localnetworkinterface',
            index=models.Index(fields=['managed_by', 'kind'], name='dashboard_l_managed_e04d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localnetworkinterface',
            unique_together={('host', 'iface_name')},
        ),
        migrations.AddIndex(
            model_name='interfaceaddress',
            index=models.Index(fields=['family', 'address'], name='dashboard_i_family_46824b_idx'),
        ),
    ]
