# Generated by Django 3.2.25 on 2025-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20250824_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown'), ('error', 'Error')], default='unknown', max_length=32)),
                ('os_type', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=128)),
                ('platform', models.CharField(blank=True, max_length=128)),
                ('cpu_count', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField(blank=True, null=True)),
                ('interfaces', models.JSONField(blank=True, null=True)),
                ('active_ports', models.JSONField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('last_command_sent', models.DateTimeField(blank=True, null=True)),
                ('last_command_result', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_interval', models.PositiveIntegerField(default=30)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.AddIndex(
            model_name='agentstatus',
            index=models.Index(fields=['agent_id'], name='dashboard_a_agent_i_0deafc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatus',
            index=models.Index(fields=['status'], name='dashboard_a_status_4bdf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatus',
            index=models.Index(fields=['last_heartbeat'], name='dashboard_a_last_he_7574b8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatus',
            index=models.Index(fields=['hostname'], name='dashboard_a_hostnam_3bd510_idx'),
        ),
    ]
