# Generated by Django 3.2.25 on 2025-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20251002_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='active_ports',
            field=models.JSONField(blank=True, help_text='Active network ports', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='cpu_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='installed_libraries',
            field=models.JSONField(blank=True, help_text='List of installed libraries/packages', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='mac_addresses',
            field=models.JSONField(blank=True, help_text='MAC addresses of network interfaces', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='memory_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='os_info',
            field=models.TextField(blank=True, help_text='Operating system information', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='platform_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
