# Generated by Django 3.2.25 on 2025-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_cyber_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='agent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='agentstatus',
            name='last_version_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
