# Generated by Django 3.2.25 on 2025-10-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_agent_version_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('network_connections', models.JSONField(blank=True, help_text='Detailed network connections with process info', null=True)),
                ('interface_statistics', models.JSONField(blank=True, help_text='Interface traffic statistics', null=True)),
                ('active_ports', models.JSONField(blank=True, help_text='Active ports and their status', null=True)),
                ('interfaces', models.JSONField(blank=True, help_text='Network interface information', null=True)),
                ('collection_duration_ms', models.FloatField(blank=True, help_text='Time taken to collect metadata', null=True)),
                ('total_connections', models.PositiveIntegerField(default=0, help_text='Total number of connections found')),
                ('total_interfaces', models.PositiveIntegerField(default=0, help_text='Total number of interfaces found')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_metadata', to='dashboard.agentstatus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField()),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.BigIntegerField(default=0)),
                ('packets_received', models.BigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='dashboard.agentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(help_text='TCP or UDP', max_length=10)),
                ('local_address', models.CharField(blank=True, max_length=255, null=True)),
                ('local_port', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_port', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(help_text='Connection status (LISTEN, ESTABLISHED, etc.)', max_length=32)),
                ('process_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('process_username', models.CharField(blank=True, max_length=255)),
                ('process_cmdline', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='dashboard.agentstatus')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='dashboard.networkmetadata')),
            ],
        ),
        migrations.AddIndex(
            model_name='networkmetadata',
            index=models.Index(fields=['agent', 'timestamp'], name='dashboard_n_agent_i_08e0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmetadata',
            index=models.Index(fields=['timestamp'], name='dashboard_n_timesta_84eb46_idx'),
        ),
        migrations.AddIndex(
            model_name='networkflow',
            index=models.Index(fields=['agent', 'protocol'], name='dashboard_n_agent_i_d58e94_idx'),
        ),
        migrations.AddIndex(
            model_name='networkflow',
            index=models.Index(fields=['source_ip', 'destination_ip', 'protocol'], name='dashboard_n_source__a5d883_idx'),
        ),
        migrations.AddIndex(
            model_name='networkflow',
            index=models.Index(fields=['first_seen'], name='dashboard_n_first_s_f897aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkflow',
            unique_together={('agent', 'source_ip', 'source_port', 'destination_ip', 'destination_port', 'protocol')},
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['agent', 'protocol'], name='dashboard_n_agent_i_db9198_idx'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['local_address', 'local_port'], name='dashboard_n_local_a_52b246_idx'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['remote_address', 'remote_port'], name='dashboard_n_remote__152d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['process_name'], name='dashboard_n_process_dcb9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='networkconnection',
            index=models.Index(fields=['status'], name='dashboard_n_status_07e214_idx'),
        ),
    ]
