# Generated by Django 3.2.25 on 2025-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20251002_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='processes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
