# Generated by Django 6.0.1 on 2026-02-20 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_research_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("cidr", models.CharField(max_length=64)),
                ("scan_method", models.CharField(choices=[("ping", "Ping"), ("openvas", "OpenVAS"), ("nmap", "Nmap"), ("agent", "Agent")], default="nmap", max_length=32)),
                ("run_openvas", models.BooleanField(default=True)),
                ("openvas_config", models.CharField(blank=True, default="full_and_fast", max_length=64)),
                ("collect_loot", models.BooleanField(default=True)),
                ("sliver_session_id", models.CharField(blank=True, max_length=128)),
                ("sliver_command", models.CharField(blank=True, default="whoami", max_length=512)),
                ("celery_task_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("RUNNING", "Running"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="PENDING", max_length=32)),
                ("current_step", models.CharField(blank=True, max_length=64)),
                ("step_message", models.CharField(blank=True, max_length=255)),
                ("steps_completed", models.PositiveSmallIntegerField(default=0)),
                ("total_steps", models.PositiveSmallIntegerField(default=4)),
                ("discovered_hosts_count", models.PositiveIntegerField(default=0)),
                ("vulnerability_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("error_details", models.TextField(blank=True)),
                ("openvas_report_id", models.CharField(blank=True, max_length=64)),
                ("result_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("openvas_scan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaign_runs", to="dashboard.scanrun")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="campaign_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campaignrun",
            index=models.Index(fields=["status", "started_at"], name="dashboard_c_status_d81750_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignrun",
            index=models.Index(fields=["cidr", "started_at"], name="dashboard_c_cidr_b93f9c_idx"),
        ),
    ]
