# Generated by Django 5.2.7 on 2025-10-03 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(help_text='Implant generation configuration')),
                ('file_format', models.CharField(default='exe', help_text='Output format (exe, dll, etc.)', max_length=50)),
                ('operating_system', models.CharField(default='windows', max_length=50)),
                ('architecture', models.CharField(default='amd64', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Implant Template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.TextField(help_text='Sliver command to execute')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Command parameters')),
                ('category', models.CharField(default='general', help_text='recon, persistence, lateral, etc.', max_length=50)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in vs custom template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teamserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this teamserver', max_length=100, unique=True)),
                ('host', models.CharField(help_text='Teamserver hostname or IP', max_length=255)),
                ('port', models.PositiveIntegerField(default=31337, help_text='Teamserver port')),
                ('ca_cert', models.TextField(blank=True, help_text='CA certificate for TLS')),
                ('private_key', models.TextField(blank=True, help_text='Private key for client authentication')),
                ('certificate', models.TextField(blank=True, help_text='Client certificate for TLS')),
                ('is_connected', models.BooleanField(default=False, help_text='Whether teamserver is currently connected')),
                ('last_connected', models.DateTimeField(blank=True, help_text='Last successful connection time', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last connection error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teamserver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Engagement name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Engagement description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organization')),
                ('target_scope', models.TextField(blank=True, help_text='Target network/IP ranges')),
                ('implant_config', models.JSONField(blank=True, default=dict, help_text='Default implant configuration')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teamserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.teamserver')),
            ],
            options={
                'verbose_name': 'Engagement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Sliver session ID', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Session name', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEAD', 'Dead'), ('DISCONNECTED', 'Disconnected')], default='ACTIVE', max_length=20)),
                ('session_type', models.CharField(choices=[('BEACON', 'Beacon'), ('SESSION', 'Interactive Session')], default='BEACON', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('uid', models.CharField(blank=True, max_length=64)),
                ('gid', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('arch', models.CharField(blank=True, max_length=50)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_privileged', models.BooleanField(default=False)),
                ('transport', models.CharField(blank=True, help_text='Communication transport (mtls, wg, http, etc.)', max_length=50)),
                ('encoder', models.CharField(blank=True, max_length=50)),
                ('reconfigure_interval', models.PositiveIntegerField(blank=True, help_text='Beacon interval in seconds', null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.engagement')),
            ],
            options={
                'verbose_name': 'Sliver Session',
                'ordering': ['-last_checkin'],
            },
        ),
        migrations.CreateModel(
            name='SliverJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='Sliver job ID', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('command', models.TextField(help_text='Executed command')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('output', models.TextField(blank=True, help_text='Command output')),
                ('error', models.TextField(blank=True, help_text='Error message')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.sliversession')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.tasktemplate')),
            ],
            options={
                'verbose_name': 'Sliver Job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot_id', models.CharField(help_text='Sliver loot ID', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('loot_type', models.CharField(choices=[('FILE', 'File'), ('CREDENTIALS', 'Credentials'), ('SYSTEM_INFO', 'System Information'), ('NETWORK_CONFIG', 'Network Configuration'), ('OTHER', 'Other')], default='FILE', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Remote file path if applicable', max_length=500)),
                ('local_path', models.FileField(blank=True, null=True, upload_to='sliver_loot/%Y/%m/%d/')),
                ('content', models.TextField(blank=True, help_text='Text content if applicable')),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.engagement')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.sliversession')),
            ],
            options={
                'verbose_name': 'Loot',
                'verbose_name_plural': 'Loot',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='SliverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Sliver event ID', max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('SESSION_OPENED', 'Session Opened'), ('SESSION_CLOSED', 'Session Closed'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('LOOT_COLLECTED', 'Loot Collected'), ('WATCHER_TRIGGERED', 'Watcher Triggered'), ('CANARY_TRIGGERED', 'Canary Triggered')], max_length=30)),
                ('data', models.JSONField(default=dict, help_text='Event-specific data')),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.engagement')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.sliversession')),
                ('teamserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.teamserver')),
            ],
            options={
                'verbose_name': 'Sliver Event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENGAGEMENT_STARTED', 'Engagement Started'), ('ENGAGEMENT_STOPPED', 'Engagement Stopped'), ('IMPLANT_GENERATED', 'Implant Generated'), ('SESSION_CONNECTED', 'Session Connected'), ('COMMAND_EXECUTED', 'Command Executed'), ('LOOT_DOWNLOADED', 'Loot Downloaded'), ('TEAMSERVER_CONNECTED', 'Teamserver Connected'), ('TEAMSERVER_DISCONNECTED', 'Teamserver Disconnected')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Action-specific details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.engagement')),
                ('loot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.loot')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.sliverjob')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sliver.sliversession')),
                ('teamserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.teamserver')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('event_filter', models.JSONField(help_text='Event filtering criteria')),
                ('action_config', models.JSONField(help_text='Automated response actions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliver.engagement')),
            ],
        ),
    ]
