# Generated by Django 5.2.10 on 2026-02-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliver', '0003_implantartifact_download_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ENGAGEMENT_STARTED', 'Engagement Started'), ('ENGAGEMENT_STOPPED', 'Engagement Stopped'), ('IMPLANT_GENERATED', 'Implant Generated'), ('IMPLANT_DEPLOYED', 'Implant Deploy Queued'), ('IMPLANT_DELIVERED', 'Implant Delivered'), ('IMPLANT_EXECUTED', 'Implant Executed'), ('IMPLANT_DEPLOY_FAILED', 'Implant Deploy Failed'), ('SESSION_CONNECTED', 'Session Connected'), ('COMMAND_EXECUTED', 'Command Executed'), ('LOOT_DOWNLOADED', 'Loot Downloaded'), ('TEAMSERVER_CONNECTED', 'Teamserver Connected'), ('TEAMSERVER_DISCONNECTED', 'Teamserver Disconnected')], max_length=50),
        ),
    ]
